apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prom-push-config
  namespace: monitoring
data:
  config.yaml: |
    node-exporter:
      namespace: "monitoring"
      scrape-every: 15
    push-gateway:
      endpoint: "http://xxx:xxx"
      project: "none"
      auth:
        username: "none"
        password: "none"
